/* ================================================================
   GeoHub — Mock Data (Georgian businesses, places, destinations)
   ================================================================ */

const BUSINESSES = [
  {
    id: 1, slug: 'rooms-hotel-kazbegi',
    name: 'Rooms Hotel Kazbegi',
    category: 'hotels', categoryLabel: 'Hotel',
    city: 'Kazbegi', region: 'Mtskheta-Mtianeti',
    lat: 42.6587, lng: 44.6406,
    rating: 4.9, reviewCount: 412,
    price: '$$$', priceFrom: 450, currency: 'GEL',
    featured: true, verified: true, premium: true,
    description: 'Perched dramatically above the Terek River valley with breathtaking views of Gergeti Trinity Church and the Kazbek glacier, Rooms Hotel Kazbegi redefines mountain luxury. Contemporary Georgian design meets world-class hospitality in this iconic property.',
    tags: ['mountain-view', 'luxury', 'spa', 'restaurant'],
    phone: '+995 322 209 000',
    whatsapp: '+995 555 100 200',
    email: 'kazbegi@roomshotels.com',
    instagram: '@roomshotelkazbegi',
    website: 'roomshotels.com',
    hours: { 'Check-in': '15:00', 'Check-out': '12:00' },
    image: 'https://picsum.photos/seed/kazbegi-hotel/800/600',
    images: [
      'https://picsum.photos/seed/kazbegi-hotel/800/600',
      'https://picsum.photos/seed/kazbegi-2/800/600',
      'https://picsum.photos/seed/kazbegi-3/800/600',
      'https://picsum.photos/seed/kazbegi-4/800/600',
    ],
    services: [
      { name: 'Superior Room', price: '450 GEL/night' },
      { name: 'Junior Suite', price: '680 GEL/night' },
      { name: 'Spa Access', price: '120 GEL/day' },
      { name: 'Guided Hike', price: '200 GEL/person' },
    ]
  },
  {
    id: 2, slug: 'kazbegi-adventures',
    name: 'Kazbegi Adventures',
    category: 'tours', categoryLabel: 'Tour Agency',
    city: 'Kazbegi', region: 'Mtskheta-Mtianeti',
    lat: 42.6540, lng: 44.6380,
    rating: 4.8, reviewCount: 248,
    price: '$$', priceFrom: 150, currency: 'GEL',
    featured: true, verified: true, premium: false,
    description: 'Leading mountain tour operator in the Greater Caucasus. We offer unforgettable hiking, trekking, 4x4 off-road adventures, and horse riding experiences guided by certified local mountain guides.',
    tags: ['hiking', 'adventure', 'mountain', '4x4'],
    phone: '+995 555 234 567',
    whatsapp: '+995 555 234 567',
    instagram: '@kazbegi_adventures',
    hours: { Mon: '09:00–19:00', Tue: '09:00–19:00', Wed: '09:00–19:00', Thu: '09:00–19:00', Fri: '09:00–19:00', Sat: '09:00–20:00', Sun: '10:00–18:00' },
    image: 'https://picsum.photos/seed/tours-1/800/600',
    images: ['https://picsum.photos/seed/tours-1/800/600','https://picsum.photos/seed/tours-2/800/600'],
    services: [
      { name: 'Gergeti Trinity Church Hike', price: '80 GEL/person' },
      { name: 'Juta Valley Trek', price: '120 GEL/person' },
      { name: '4x4 Mountain Safari', price: '280 GEL/group' },
      { name: 'Horse Riding', price: '150 GEL/person' },
    ]
  },
  {
    id: 3, slug: 'shavi-lomi-restaurant',
    name: 'Shavi Lomi',
    category: 'restaurants', categoryLabel: 'Restaurant',
    city: 'Tbilisi', region: 'Vake',
    lat: 41.7070, lng: 44.7693,
    rating: 4.7, reviewCount: 1024,
    price: '$$$', priceFrom: 40, currency: 'GEL',
    featured: true, verified: true, premium: true,
    description: 'Award-winning contemporary Georgian cuisine in the heart of Tbilisi. Chef Meriko Gubeladze reimagines traditional recipes using locally sourced, seasonal ingredients. Stunning interiors with exposed brick and warm lighting.',
    tags: ['fine-dining', 'georgian-cuisine', 'wine', 'romantic'],
    phone: '+995 322 917 501',
    instagram: '@shavilomi_tbilisi',
    hours: { Mon: 'Closed', Tue: '13:00–23:00', Wed: '13:00–23:00', Thu: '13:00–23:00', Fri: '13:00–00:00', Sat: '12:00–00:00', Sun: '12:00–22:00' },
    image: 'https://picsum.photos/seed/restaurant-1/800/600',
    images: ['https://picsum.photos/seed/restaurant-1/800/600','https://picsum.photos/seed/restaurant-2/800/600'],
    services: [
      { name: 'Khinkali (6 pcs)', price: '12 GEL' },
      { name: 'Khachapuri Adjaruli', price: '18 GEL' },
      { name: 'Chakapuli (Spring stew)', price: '28 GEL' },
      { name: 'Wine Selection (glass)', price: '12–35 GEL' },
    ]
  },
  {
    id: 4, slug: 'fabrika-hostel-tbilisi',
    name: 'Fabrika Hostel & Suites',
    category: 'hotels', categoryLabel: 'Hostel / Boutique',
    city: 'Tbilisi', region: 'Chugureti',
    lat: 41.6941, lng: 44.8017,
    rating: 4.6, reviewCount: 789,
    price: '$', priceFrom: 60, currency: 'GEL',
    featured: false, verified: true, premium: false,
    description: 'The iconic Soviet sewing factory turned creative hub. Fabrika is more than a hostel — it is a community space with co-working, rooftop bar, food trucks, boutique shops, and live music.',
    tags: ['boutique', 'hipster', 'rooftop', 'co-working'],
    phone: '+995 322 137 003',
    instagram: '@fabrika.tbilisi',
    hours: { 'Check-in': '14:00', 'Check-out': '11:00' },
    image: 'https://picsum.photos/seed/hostel-fab/800/600',
    images: ['https://picsum.photos/seed/hostel-fab/800/600'],
    services: [
      { name: 'Dorm Bed', price: '60 GEL/night' },
      { name: 'Private Room', price: '120 GEL/night' },
      { name: 'Suite', price: '220 GEL/night' },
    ]
  },
  {
    id: 5, slug: 'kakheti-wine-experience',
    name: 'Kakheti Wine Experience',
    category: 'tours', categoryLabel: 'Wine Tour',
    city: 'Telavi', region: 'Kakheti',
    lat: 41.9183, lng: 45.4742,
    rating: 4.9, reviewCount: 173,
    price: '$$', priceFrom: 120, currency: 'GEL',
    featured: true, verified: true, premium: true,
    description: 'Discover the birthplace of wine. Full-day wine tours through the Kakheti region visiting ancient family wineries, underground cellars, and stunning vineyards with Alazani Valley views.',
    tags: ['wine', 'culture', 'countryside', 'family-friendly'],
    phone: '+995 555 987 654',
    whatsapp: '+995 555 987 654',
    instagram: '@kakheti_wine_tours',
    hours: { Mon: '09:00–18:00', Tue: '09:00–18:00', Wed: '09:00–18:00', Thu: '09:00–18:00', Fri: '09:00–18:00', Sat: '09:00–18:00', Sun: '10:00–17:00' },
    image: 'https://picsum.photos/seed/wine-tour/800/600',
    images: ['https://picsum.photos/seed/wine-tour/800/600','https://picsum.photos/seed/wine-2/800/600'],
    services: [
      { name: 'Full Day Wine Tour', price: '120 GEL/person' },
      { name: 'Winery Lunch & Tasting', price: '80 GEL/person' },
      { name: 'Private Tour (up to 4)', price: '350 GEL' },
    ]
  },
  {
    id: 6, slug: 'old-tbilisi-cafe-gallery',
    name: 'Old Tbilisi Café & Gallery',
    category: 'cafes', categoryLabel: 'Café',
    city: 'Tbilisi', region: 'Old Town',
    lat: 41.6876, lng: 44.8090,
    rating: 4.5, reviewCount: 634,
    price: '$', priceFrom: 8, currency: 'GEL',
    featured: false, verified: true, premium: false,
    description: 'A charming café in the winding streets of Old Tbilisi, where local art meets traditional Georgian coffee and sweets. Featuring original artworks by local painters, with a cozy rooftop terrace overlooking the Metekhi Church.',
    tags: ['art', 'coffee', 'rooftop', 'cozy'],
    phone: '+995 555 111 222',
    instagram: '@oldtbilisi_cafe',
    hours: { Mon: '09:00–22:00', Tue: '09:00–22:00', Wed: '09:00–22:00', Thu: '09:00–22:00', Fri: '09:00–00:00', Sat: '10:00–00:00', Sun: '10:00–22:00' },
    image: 'https://picsum.photos/seed/cafe-1/800/600',
    images: ['https://picsum.photos/seed/cafe-1/800/600'],
    services: [
      { name: 'Georgian Coffee', price: '5 GEL' },
      { name: 'Churchkhela', price: '6 GEL' },
      { name: 'Breakfast Set', price: '18 GEL' },
    ]
  },
  {
    id: 7, slug: 'batumi-sheraton',
    name: 'Sheraton Batumi Hotel',
    category: 'hotels', categoryLabel: 'Hotel',
    city: 'Batumi', region: 'Adjara',
    lat: 41.6405, lng: 41.6372,
    rating: 4.7, reviewCount: 956,
    price: '$$$', priceFrom: 380, currency: 'GEL',
    featured: false, verified: true, premium: true,
    description: 'Luxury seafront hotel on the Black Sea coast with direct beach access. Modern rooms with panoramic ocean views, outdoor infinity pool, spa, and multiple restaurants.',
    tags: ['beach', 'luxury', 'sea-view', 'pool', 'spa'],
    phone: '+995 422 260 000',
    instagram: '@sheratonbatumi',
    hours: { 'Check-in': '15:00', 'Check-out': '12:00' },
    image: 'https://picsum.photos/seed/batumi-hotel/800/600',
    images: ['https://picsum.photos/seed/batumi-hotel/800/600'],
    services: [
      { name: 'Sea View Room', price: '380 GEL/night' },
      { name: 'Deluxe Suite', price: '650 GEL/night' },
      { name: 'Beach Access', price: 'Free for guests' },
    ]
  },
  {
    id: 8, slug: 'mestia-svan-guesthouse',
    name: 'Svan Guesthouse Mestia',
    category: 'guesthouses', categoryLabel: 'Guesthouse',
    city: 'Mestia', region: 'Svaneti',
    lat: 43.0500, lng: 42.7260,
    rating: 4.8, reviewCount: 189,
    price: '$', priceFrom: 80, currency: 'GEL',
    featured: false, verified: true, premium: false,
    description: 'Traditional Svan stone tower guesthouse in the UNESCO World Heritage town of Mestia. Authentic home-cooked meals, local wine, and the warmest mountain hospitality. Perfect base for trekking in the Upper Svaneti.',
    tags: ['mountain', 'hiking', 'traditional', 'family-run'],
    phone: '+995 557 345 678',
    whatsapp: '+995 557 345 678',
    instagram: '@svan_guesthouse',
    hours: { 'Check-in': '13:00', 'Check-out': '11:00' },
    image: 'https://picsum.photos/seed/mestia/800/600',
    images: ['https://picsum.photos/seed/mestia/800/600'],
    services: [
      { name: 'Room with Breakfast', price: '80 GEL/person' },
      { name: 'Full Board', price: '120 GEL/person' },
      { name: 'Trekking Guide', price: '100 GEL/day' },
    ]
  },
  {
    id: 9, slug: 'narikala-tours',
    name: 'Narikala Old Tbilisi Tours',
    category: 'tours', categoryLabel: 'City Tour',
    city: 'Tbilisi', region: 'Old Town',
    lat: 41.6877, lng: 44.8120,
    rating: 4.6, reviewCount: 302,
    price: '$', priceFrom: 50, currency: 'GEL',
    featured: false, verified: true, premium: false,
    description: 'Guided walking tours through the historic streets of Old Tbilisi. Visit Narikala Fortress, Sulfur Baths, Metekhi Church, the Persian Mosque, and the colorful Abanotubani district with an expert local guide.',
    tags: ['walking-tour', 'history', 'culture', 'old-city'],
    phone: '+995 591 223 344',
    whatsapp: '+995 591 223 344',
    instagram: '@narikala_tours',
    hours: { Mon: '09:00–19:00', Tue: '09:00–19:00', Wed: '09:00–19:00', Thu: '09:00–19:00', Fri: '09:00–19:00', Sat: '09:00–19:00', Sun: '09:00–17:00' },
    image: 'https://picsum.photos/seed/tbilisi-tour/800/600',
    images: ['https://picsum.photos/seed/tbilisi-tour/800/600'],
    services: [
      { name: 'Old Tbilisi Walking Tour (3h)', price: '50 GEL/person' },
      { name: 'Private Tour (up to 6)', price: '200 GEL' },
      { name: 'Full City Day Tour', price: '100 GEL/person' },
    ]
  },
  {
    id: 10, slug: 'gudauri-ski-resort',
    name: 'Gudauri Ski Resort',
    category: 'attractions', categoryLabel: 'Attraction',
    city: 'Gudauri', region: 'Mtskheta-Mtianeti',
    lat: 42.4793, lng: 44.4773,
    rating: 4.5, reviewCount: 2104,
    price: '$$', priceFrom: 80, currency: 'GEL',
    featured: true, verified: true, premium: true,
    description: 'Georgia\'s premier ski destination at 2000–3279m altitude in the Greater Caucasus. Over 70km of ski runs for all levels, modern gondola lifts, and stunning views of the Caucasus mountain range.',
    tags: ['skiing', 'snowboard', 'mountain', 'winter', 'adventure'],
    phone: '+995 322 187 777',
    instagram: '@gudauri_ski',
    website: 'gudauri.ge',
    hours: { 'Season': 'Dec–Apr', 'Daily': '09:00–17:00' },
    image: 'https://picsum.photos/seed/gudauri/800/600',
    images: ['https://picsum.photos/seed/gudauri/800/600'],
    services: [
      { name: 'Day Ski Pass', price: '80 GEL' },
      { name: 'Week Pass', price: '320 GEL' },
      { name: 'Ski Rental', price: '60 GEL/day' },
      { name: 'Ski Lessons', price: '120 GEL/2h' },
    ]
  },
  {
    id: 11, slug: 'borjomi-mineral-spa',
    name: 'Borjomi Mineral Spa & Resort',
    category: 'hotels', categoryLabel: 'Spa Resort',
    city: 'Borjomi', region: 'Samtskhe-Javakheti',
    lat: 41.8389, lng: 43.3867,
    rating: 4.6, reviewCount: 421,
    price: '$$$', priceFrom: 320, currency: 'GEL',
    featured: false, verified: true, premium: false,
    description: 'Luxury spa resort in the famous Borjomi mineral water valley. Treatments using natural mineral springs, surrounded by the Borjomi-Kharagauli National Park.',
    tags: ['spa', 'wellness', 'nature', 'mineral-water'],
    phone: '+995 367 222 222',
    image: 'https://picsum.photos/seed/borjomi/800/600',
    images: ['https://picsum.photos/seed/borjomi/800/600'],
    services: [
      { name: 'Mineral Pool Access', price: '60 GEL' },
      { name: 'Deluxe Room', price: '320 GEL/night' },
      { name: 'Spa Day Package', price: '180 GEL/person' },
    ]
  },
  {
    id: 12, slug: 'sighnaghi-winery-lodge',
    name: 'Sighnaghi Wine & Lodge',
    category: 'guesthouses', categoryLabel: 'Wine Lodge',
    city: 'Sighnaghi', region: 'Kakheti',
    lat: 41.6167, lng: 45.9333,
    rating: 4.8, reviewCount: 267,
    price: '$$', priceFrom: 150, currency: 'GEL',
    featured: false, verified: true, premium: false,
    description: 'Boutique wine lodge in the "City of Love" with sweeping views of the Alazani Valley. Produce our own natural wine using Rkatsiteli and Saperavi grapes in traditional Qvevri clay vessels.',
    tags: ['wine', 'romantic', 'vineyard-view', 'boutique'],
    phone: '+995 555 678 901',
    instagram: '@sighnaghi_wine',
    image: 'https://picsum.photos/seed/sighnaghi/800/600',
    images: ['https://picsum.photos/seed/sighnaghi/800/600'],
    services: [
      { name: 'Room with Valley View', price: '150 GEL/night' },
      { name: 'Wine Tasting (5 wines)', price: '45 GEL/person' },
    ]
  }
];

const DESTINATIONS = [
  {
    id: 1, name: 'Tbilisi', slug: 'tbilisi',
    description: 'Ancient capital with sulfur baths & vibrant old town',
    count: 342, region: 'Capital',
    featured: true,
    image: 'https://picsum.photos/seed/tbilisi-city/1200/800',
    highlights: ['Old Town', 'Narikala Fortress', 'Wine bars', 'Museums']
  },
  {
    id: 2, name: 'Kazbegi', slug: 'kazbegi',
    description: 'Iconic mountain village beneath Mt. Kazbek',
    count: 87, region: 'Mtskheta-Mtianeti',
    featured: false,
    image: 'https://picsum.photos/seed/kazbegi-dest/800/600',
    highlights: ['Gergeti Trinity Church', 'Hiking', 'Mountain views', 'Adventure']
  },
  {
    id: 3, name: 'Batumi', slug: 'batumi',
    description: 'Georgian riviera on the Black Sea coast',
    count: 198, region: 'Adjara',
    featured: false,
    image: 'https://picsum.photos/seed/batumi-dest/800/600',
    highlights: ['Black Sea Beach', 'Botanical Garden', 'Nightlife', 'Architecture']
  },
  {
    id: 4, name: 'Sighnaghi', slug: 'sighnaghi',
    description: 'Romantic walled city in the wine region',
    count: 64, region: 'Kakheti',
    featured: false,
    image: 'https://picsum.photos/seed/sighnaghi-dest/800/600',
    highlights: ['Wine tasting', 'Panoramic views', 'Old walls', 'Crafts']
  },
  {
    id: 5, name: 'Gudauri', slug: 'gudauri',
    description: 'Premier ski resort in the Caucasus mountains',
    count: 52, region: 'Mtskheta-Mtianeti',
    featured: false,
    image: 'https://picsum.photos/seed/gudauri-dest/800/600',
    highlights: ['Skiing', 'Snowboard', 'Mountain views', 'Winter sports']
  },
  {
    id: 6, name: 'Mestia', slug: 'mestia',
    description: 'Medieval Svan towers in UNESCO heritage Svaneti',
    count: 43, region: 'Svaneti',
    featured: false,
    image: 'https://picsum.photos/seed/mestia-dest/800/600',
    highlights: ['Svan Towers', 'Trekking', 'Culture', 'Glaciers']
  }
];

const CATEGORIES = [
  { id: 'tours', icon: '🗺️', name: 'Tours', count: 148 },
  { id: 'cafes', icon: '☕', name: 'Cafés', count: 214 },
  { id: 'restaurants', icon: '🍽️', name: 'Restaurants', count: 389 },
  { id: 'hotels', icon: '🏨', name: 'Hotels', count: 176 },
  { id: 'guesthouses', icon: '🏡', name: 'Guesthouses', count: 93 },
  { id: 'hiking', icon: '🥾', name: 'Hiking', count: 67 },
  { id: 'camping', icon: '⛺', name: 'Camping', count: 38 },
  { id: 'attractions', icon: '🏛️', name: 'Attractions', count: 124 },
  { id: 'guides', icon: '🧭', name: 'Guides', count: 55 },
  { id: '4x4', icon: '🚙', name: '4×4 Routes', count: 29 },
  { id: 'beauty', icon: '💆', name: 'Beauty', count: 84 },
  { id: 'dental', icon: '🦷', name: 'Dental', count: 47 },
];

const REVIEWS = [
  { id: 1, businessId: 1, author: 'Sarah M.', avatar: 'S', rating: 5, date: '2024-11-12', text: 'Absolutely stunning hotel! The views of Gergeti Trinity Church from our room were indescribable. The staff was incredibly warm and helpful with arranging our hike.' },
  { id: 2, businessId: 1, author: 'James K.', avatar: 'J', rating: 5, date: '2024-10-28', text: 'One of the best hotel experiences I\'ve ever had. The design is beautiful and feels authentically Georgian. The restaurant serves excellent local food.' },
  { id: 3, businessId: 1, author: 'Nino G.', avatar: 'N', rating: 4, date: '2024-09-15', text: 'Wonderful place, highly recommend for anyone visiting Kazbegi. The only small issue was slow WiFi in the rooms, but everything else was perfect.' },
  { id: 4, businessId: 2, author: 'Mike T.', avatar: 'M', rating: 5, date: '2024-11-01', text: 'Our guide Giorgi was fantastic! Very knowledgeable about the mountains and history. The 4x4 tour was the highlight of our whole Georgia trip.' },
];

const STATS = {
  businesses: 1842,
  cities: 47,
  users: 28600,
  reviews: 14300
};
