$f = 'business-page.js'
$c = [IO.File]::ReadAllText($f, [Text.Encoding]::UTF8)

$pairs = @(
  @("showToast('Could not save: ' + (err.code || err.message), false)", "showToast(_bpt('post_save_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not update: ' + (err.code || err.message), false)", "showToast(_bpt('update_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not delete: ' + (err.code || err.message), false)", "showToast(_bpt('post_del_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not delete: '+(err.code||err.message), false)", "showToast(_bpt('post_del_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not edit: '+(err.code||err.message), false)", "showToast(_bpt('comment_edit_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Delete failed: '+(err.code||err.message), false)", "showToast(_bpt('post_del_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not delete reply: '+(err.code||err.message), false)", "showToast(_bpt('reply_del_fail2')+': '+(err.code||err.message), false)"),
  @("showToast('Could not delete reply', false)", "showToast(_bpt('reply_del_fail2'), false)"),
  @("showToast('Could not edit reply', false)", "showToast(_bpt('reply_edit_fail'), false)"),
  @("showToast('Could not post reply: '+(err.code||err.message), false)", "showToast(_bpt('reply_post_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not add FAQ: '+(err.code||err.message), false)", "showToast(_bpt('faq_add_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not add admin: '+(err.code||err.message), false)", "showToast(_bpt('admin_add_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not add milestone: '+(err.code||err.message), false)", "showToast(_bpt('milestone_add_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not create event: '+(err.code||err.message), false)", "showToast(_bpt('event_create_fail')+': '+(err.code||err.message), false)"),
  @("showToast('Could not remove admin', false)", "showToast(_bpt('admin_remove_fail'), false)"),
  @("showToast('Could not add block', false)", "showToast(_bpt('block_add_fail'), false)"),
  @("showToast('Could not reorder', false)", "showToast(_bpt('reorder_fail'), false)"),
  @("showToast('Could not update priority', false)", "showToast(_bpt('priority_fail'), false)"),
  @("showToast('Could not update status', false)", "showToast(_bpt('status_fail'), false)"),
  @("showToast('Could not send. Try again.', false)", "showToast(_bpt('send_fail'), false)"),
  @("showToast('Could not save RSVP', false)", "showToast(_bpt('rsvp_save_fail'), false)"),
  @("showToast('Could not save note', false)", "showToast(_bpt('note_save_fail'), false)"),
  @("showToast('Could not submit question', false)", "showToast(_bpt('question_sub_fail'), false)"),
  @("showToast('Could not like', false)", "showToast(_bpt('soc_reaction_fail'), false)"),
  @("showToast('Cover photo updated!')", "showToast(_bpt('cover_updated'))"),
  @("showToast('Logo updated!')", "showToast(_bpt('logo_updated'))"),
  @("showToast('Photo added!')", "showToast(_bpt('photo_added'))"),
  @("showToast('Photo deleted')", "showToast(_bpt('photo_deleted'))"),
  @("showToast('Review posted!')", "showToast(_bpt('review_posted'))"),
  @("showToast('Review deleted')", "showToast(_bpt('review_deleted_done'))"),
  @("showToast('Could not post review', false)", "showToast(_bpt('review_post_fail'), false)"),
  @("showToast('Please write a review', false)", "showToast(_bpt('please_write_review'), false)"),
  @("showToast('Please select a star rating', false)", "showToast(_bpt('please_rate'), false)"),
  @("showToast('Event created!')", "showToast(_bpt('event_created'))"),
  @("showToast('Event name and date are required', false)", "showToast(_bpt('event_date_req'), false)"),
  @("showToast('Product added!')", "showToast(_bpt('product_added'))"),
  @("showToast('Product deleted')", "showToast(_bpt('product_deleted_done'))"),
  @("showToast('Product name is required', false)", "showToast(_bpt('product_name_req'), false)"),
  @("showToast('Service deleted')", "showToast(_bpt('service_deleted_done'))"),
  @("showToast('Service name is required', false)", "showToast(_bpt('service_name_req'), false)"),
  @("showToast('Service not found', false)", "showToast(_bpt('service_not_found'), false)"),
  @("showToast('Could not load service', false)", "showToast(_bpt('could_not_load_svc'), false)"),
  @("showToast('FAQ item added!')", "showToast(_bpt('faq_added'))"),
  @("showToast('Added to FAQ!')", "showToast(_bpt('faq_added'))"),
  @("showToast('FAQ item deleted')", "showToast(_bpt('faq_deleted_done'))"),
  @("showToast('Could not add to FAQ', false)", "showToast(_bpt('faq_add_fail'), false)"),
  @("showToast('Milestone added!')", "showToast(_bpt('milestone_added'))"),
  @("showToast('Milestone deleted')", "showToast(_bpt('milestone_deleted_done'))"),
  @("showToast('Comment updated')", "showToast(_bpt('comment_updated'))"),
  @("showToast('Comment deleted')", "showToast(_bpt('comment_deleted'))"),
  @("showToast('Reply posted!')", "showToast(_bpt('reply_posted'))"),
  @("showToast('Reply updated')", "showToast(_bpt('reply_updated_done'))"),
  @("showToast('Reply deleted')", "showToast(_bpt('reply_del_done'))"),
  @("showToast('Could not post reply', false)", "showToast(_bpt('reply_post_fail'), false)"),
  @("showToast('Reply cannot be empty', false)", "showToast(_bpt('reply_empty'), false)"),
  @("showToast('Sign in to RSVP', false)", "showToast(_bpt('sign_in_to_rsvp'), false)"),
  @("showToast('Sign in to like posts', false)", "showToast(_bpt('sign_in_to_like'), false)"),
  @("showToast('Sign in to message this page', false)", "showToast(_bpt('sign_in_to_msg'), false)"),
  @("showToast('Sign in to request a quote', false)", "showToast(_bpt('sign_in_to_quote'), false)"),
  @("showToast('Sign in to ask a question', false)", "showToast(_bpt('sign_in_to_ask'), false)"),
  @("showToast('Sign in to reply', false)", "showToast(_bpt('sign_in_to_reply'), false)"),
  @("showToast('Sign in to post', false)", "showToast(_bpt('sign_in_to_post'), false)"),
  @("showToast('Sign in to review', false)", "showToast(_bpt('sign_in_to_review'), false)"),
  @("showToast('Please sign in', false)", "showToast(_bpt('please_sign_in'), false)"),
  @("showToast('Sign in to save',false)", "showToast(_bpt('sign_in_to_save'),false)"),
  @("showToast('Saved!')", "showToast(_bpt('saved_done'))"),
  @("showToast('Shared!')", "showToast(_bpt('shared_done'))"),
  @("showToast('Posted!')", "showToast(_bpt('posted_done'))"),
  @("showToast('Could not remove',false)", "showToast(_bpt('share_fail'),false)"),
  @("showToast('Could not save',false)", "showToast(_bpt('post_save_fail'),false)"),
  @("showToast('Could not copy', false)", "showToast(_bpt('could_not_copy'), false)"),
  @("showToast('Link copied!')", "showToast(_bpt('link_copied'))"),
  @("showToast('Admin added!')", "showToast(_bpt('admin_added'))"),
  @("showToast('Admin removed')", "showToast(_bpt('admin_removed_done'))"),
  @("showToast('Price item added!')", "showToast(_bpt('price_added'))"),
  @("showToast('Price item removed')", "showToast(_bpt('price_removed'))"),
  @("showToast('Block added!')", "showToast(_bpt('block_added'))"),
  @("showToast('Block deleted')", "showToast(_bpt('block_deleted_done'))"),
  @("showToast('Block updated!')", "showToast(_bpt('block_updated_done'))"),
  @("showToast('Business page deleted')", "showToast(_bpt('biz_deleted'))"),
  @("showToast('Question submitted!')", "showToast(_bpt('question_submitted'))"),
  @("showToast('Answer saved')", "showToast(_bpt('answer_saved'))"),
  @("showToast('Note saved')", "showToast(_bpt('note_saved'))"),
  @("showToast('Quote request sent!')", "showToast(_bpt('quote_sent'))"),
  @("showToast('Please fill in name, email, and message', false)", "showToast(_bpt('please_fill_contact'), false)"),
  @("showToast('Please enter a question', false)", "showToast(_bpt('please_enter_q'), false)"),
  @("showToast('Add a title or content', false)", "showToast(_bpt('add_title_content'), false)"),
  @("showToast('Write something or add a photo', false)", "showToast(_bpt('write_something'), false)"),
  @("showToast('Name and price are required', false)", "showToast(_bpt('name_price_req'), false)"),
  @("showToast('Question and answer are required', false)", "showToast(_bpt('q_and_a_req'), false)"),
  @("showToast('Title and date are required', false)", "showToast(_bpt('title_date_req'), false)"),
  @("showToast('User ID and role are required', false)", "showToast(_bpt('uid_role_req'), false)"),
  @("showToast('Type DELETE to confirm', false)", "showToast(_bpt('type_delete_cfm'), false)"),
  @("showToast('Business page post composer is being rebuilt.', false)", "showToast(_bpt('biz_rebuild'), false)")
)

foreach ($pair in $pairs) { $c = $c.Replace($pair[0], $pair[1]) }
[IO.File]::WriteAllText($f, $c, [Text.Encoding]::UTF8)
Write-Host 'Done'
