/* GeoHub mock social graph for frontend testing only. No auth, no backend. */

const MOCK_USERS = [
  { id: 'u01', fullName: 'Nino Gelashvili', username: 'nino.explorer', avatar: 'https://picsum.photos/seed/gh-nino/200/200', coverImage: 'https://picsum.photos/seed/gh-nino-cover/1200/500', bio: 'Active explorer collecting cafes, events, and hidden corners of Tbilisi.', city: 'Tbilisi', explorerLevel: 'Gold Explorer', xp: 8420, rank: 14, badges: ['Cafe Hunter', 'Weekend Explorer', 'Top Reviewer'], interests: ['cafes', 'events', 'photography'], followers: 1240, following: 318, postsCount: 186, visitedPlaces: 148, trustScore: 94, accountType: 'Creator' },
  { id: 'u02', fullName: 'Luka Abashidze', username: 'luka.mountain', avatar: 'https://picsum.photos/seed/gh-luka/200/200', coverImage: 'https://picsum.photos/seed/gh-luka-cover/1200/500', bio: 'Mountain routes, early starts, and honest trail notes.', city: 'Kazbegi', explorerLevel: 'Platinum Explorer', xp: 15680, rank: 3, badges: ['Mountain Lover', 'Hidden Spot Finder', 'City Expert'], interests: ['hiking', 'camping', 'routes'], followers: 3410, following: 205, postsCount: 312, visitedPlaces: 276, trustScore: 98, accountType: 'Creator' },
  { id: 'u03', fullName: 'Mariam Chikovanidze', username: 'mari.cafe', avatar: 'https://picsum.photos/seed/gh-mari/200/200', coverImage: 'https://picsum.photos/seed/gh-mari-cover/1200/500', bio: 'Quiet corners, good coffee, and laptop-friendly spots.', city: 'Tbilisi', explorerLevel: 'Silver Explorer', xp: 3920, rank: 88, badges: ['Cafe Hunter', 'Shy Reviewer'], interests: ['cafes', 'remote work', 'books'], followers: 426, following: 190, postsCount: 72, visitedPlaces: 64, trustScore: 89, accountType: 'Explorer' },
  { id: 'u04', fullName: 'Giorgi Beridze', username: 'giorgi.tastes', avatar: 'https://picsum.photos/seed/gh-giorgi/200/200', coverImage: 'https://picsum.photos/seed/gh-giorgi-cover/1200/500', bio: 'Food reviewer hunting the best khinkali, wine bars, and family kitchens.', city: 'Tbilisi', explorerLevel: 'Gold Explorer', xp: 7710, rank: 21, badges: ['Top Reviewer', 'Food Scout', 'Wine Route'], interests: ['restaurants', 'wine', 'reviews'], followers: 1815, following: 402, postsCount: 244, visitedPlaces: 199, trustScore: 96, accountType: 'Creator' },
  { id: 'u05', fullName: 'Ana Kvaratskhelia', username: 'ana.green', avatar: 'https://picsum.photos/seed/gh-ana/200/200', coverImage: 'https://picsum.photos/seed/gh-ana-cover/1200/500', bio: 'Community helper, cleanup organizer, and weekend nature person.', city: 'Kutaisi', explorerLevel: 'Gold Explorer', xp: 6900, rank: 34, badges: ['Patriot', 'Community Helper', 'Weekend Explorer'], interests: ['patriot tasks', 'parks', 'hiking'], followers: 980, following: 266, postsCount: 128, visitedPlaces: 117, trustScore: 97, accountType: 'Patriot' },
  { id: 'u06', fullName: 'Tamo Jikia', username: 'tamo.vibes', avatar: 'https://picsum.photos/seed/gh-tamo/200/200', coverImage: 'https://picsum.photos/seed/gh-tamo-cover/1200/500', bio: 'Night markets, concerts, DJ sets, and group plans.', city: 'Tbilisi', explorerLevel: 'Silver Explorer', xp: 4580, rank: 61, badges: ['Event Addict', 'Social Connector'], interests: ['nightlife', 'events', 'groups'], followers: 2030, following: 612, postsCount: 154, visitedPlaces: 82, trustScore: 86, accountType: 'Creator' },
  { id: 'u07', fullName: 'Sandro Maisuradze', username: 'sandro.frames', avatar: 'https://picsum.photos/seed/gh-sandro/200/200', coverImage: 'https://picsum.photos/seed/gh-sandro-cover/1200/500', bio: 'Street photographer posting aesthetic places and golden-hour walks.', city: 'Tbilisi', explorerLevel: 'Gold Explorer', xp: 6120, rank: 39, badges: ['Hidden Spot Finder', 'City Expert'], interests: ['photography', 'architecture', 'hidden spots'], followers: 2760, following: 340, postsCount: 221, visitedPlaces: 132, trustScore: 92, accountType: 'Creator' },
  { id: 'u08', fullName: 'Elene Tsiklauri', username: 'elene.student', avatar: 'https://picsum.photos/seed/gh-elene/200/200', coverImage: 'https://picsum.photos/seed/gh-elene-cover/1200/500', bio: 'Student looking for free events, study cafes, and cheap weekend plans.', city: 'Tbilisi', explorerLevel: 'Bronze Explorer', xp: 1280, rank: 244, badges: ['Budget Traveler'], interests: ['free events', 'cafes', 'student deals'], followers: 210, following: 188, postsCount: 31, visitedPlaces: 29, trustScore: 78, accountType: 'Student' },
  { id: 'u09', fullName: 'Dato Mchedlishvili', username: 'dato.moves', avatar: 'https://picsum.photos/seed/gh-dato/200/200', coverImage: 'https://picsum.photos/seed/gh-dato-cover/1200/500', bio: 'Fitness routes, running clubs, healthy cafes, and sports events.', city: 'Batumi', explorerLevel: 'Silver Explorer', xp: 3610, rank: 104, badges: ['Weekend Explorer', 'Fitness Streak'], interests: ['fitness', 'running', 'healthy food'], followers: 640, following: 271, postsCount: 86, visitedPlaces: 58, trustScore: 88, accountType: 'Explorer' },
  { id: 'u10', fullName: 'Salome Dolidze', username: 'salome.luxe', avatar: 'https://picsum.photos/seed/gh-salome/200/200', coverImage: 'https://picsum.photos/seed/gh-salome-cover/1200/500', bio: 'Boutique hotels, spa weekends, fine dining, and premium rewards.', city: 'Batumi', explorerLevel: 'Gold Explorer', xp: 7040, rank: 29, badges: ['Luxury Lifestyle', 'Top Reviewer'], interests: ['hotels', 'spa', 'fine dining'], followers: 4120, following: 520, postsCount: 202, visitedPlaces: 121, trustScore: 91, accountType: 'Creator' },
  { id: 'u11', fullName: 'Irakli Nozadze', username: 'irakli.budget', avatar: 'https://picsum.photos/seed/gh-irakli/200/200', coverImage: 'https://picsum.photos/seed/gh-irakli-cover/1200/500', bio: 'Budget traveler proving you can explore Georgia without spending much.', city: 'Rustavi', explorerLevel: 'Silver Explorer', xp: 2870, rank: 138, badges: ['Budget Traveler', 'District Explorer'], interests: ['cheap eats', 'transport', 'hostels'], followers: 518, following: 333, postsCount: 79, visitedPlaces: 74, trustScore: 84, accountType: 'Explorer' },
  { id: 'u12', fullName: 'Medea Sharashidze', username: 'medea.hidden', avatar: 'https://picsum.photos/seed/gh-medea/200/200', coverImage: 'https://picsum.photos/seed/gh-medea-cover/1200/500', bio: 'Hidden courtyards, small museums, and places people walk past too fast.', city: 'Tbilisi', explorerLevel: 'Platinum Explorer', xp: 12140, rank: 7, badges: ['Hidden Spot Finder', 'City Expert', 'Top Reviewer'], interests: ['hidden spots', 'history', 'museums'], followers: 1890, following: 215, postsCount: 280, visitedPlaces: 310, trustScore: 99, accountType: 'Explorer' },
  { id: 'u13', fullName: 'Levan Khurtsidze', username: 'levan.nights', avatar: 'https://picsum.photos/seed/gh-levan/200/200', coverImage: 'https://picsum.photos/seed/gh-levan-cover/1200/500', bio: 'Party person with honest nightlife reviews and late dinner maps.', city: 'Tbilisi', explorerLevel: 'Silver Explorer', xp: 4010, rank: 77, badges: ['Event Addict', 'Social Connector'], interests: ['nightlife', 'bars', 'music'], followers: 1540, following: 760, postsCount: 119, visitedPlaces: 69, trustScore: 81, accountType: 'Explorer' },
  { id: 'u14', fullName: 'Sofia Keller', username: 'sofia.in.georgia', avatar: 'https://picsum.photos/seed/gh-sofia/200/200', coverImage: 'https://picsum.photos/seed/gh-sofia-cover/1200/500', bio: 'Traveler documenting Georgia slowly, one region at a time.', city: 'Tbilisi', explorerLevel: 'Gold Explorer', xp: 8350, rank: 16, badges: ['Traveler', 'Weekend Explorer'], interests: ['travel', 'wine', 'routes'], followers: 2310, following: 440, postsCount: 175, visitedPlaces: 166, trustScore: 93, accountType: 'Creator' },
  { id: 'u15', fullName: 'Nika Tavartkiladze', username: 'nika.estates', avatar: 'https://picsum.photos/seed/gh-nika/200/200', coverImage: 'https://picsum.photos/seed/gh-nika-cover/1200/500', bio: 'Neighborhood walks, new developments, cafes near apartments, and city value.', city: 'Tbilisi', explorerLevel: 'Bronze Explorer', xp: 1720, rank: 198, badges: ['District Explorer'], interests: ['real estate', 'districts', 'cafes'], followers: 330, following: 410, postsCount: 42, visitedPlaces: 38, trustScore: 80, accountType: 'Explorer' },
  { id: 'u16', fullName: 'Keti Lomidze', username: 'keti.learns', avatar: 'https://picsum.photos/seed/gh-keti/200/200', coverImage: 'https://picsum.photos/seed/gh-keti-cover/1200/500', bio: 'Teacher and course creator sharing workshops, study spaces, and book clubs.', city: 'Tbilisi', explorerLevel: 'Silver Explorer', xp: 3350, rank: 112, badges: ['Event Addict', 'Community Helper'], interests: ['courses', 'workshops', 'books'], followers: 780, following: 295, postsCount: 97, visitedPlaces: 57, trustScore: 90, accountType: 'Teacher' },
  { id: 'u17', fullName: 'Beka Arabuli', username: 'beka.nomad', avatar: 'https://picsum.photos/seed/gh-beka/200/200', coverImage: 'https://picsum.photos/seed/gh-beka-cover/1200/500', bio: 'Remote worker testing Wi-Fi, outlets, and calm corners across Georgia.', city: 'Telavi', explorerLevel: 'Bronze Explorer', xp: 2180, rank: 161, badges: ['Cafe Hunter'], interests: ['coworking', 'cafes', 'travel'], followers: 410, following: 250, postsCount: 55, visitedPlaces: 46, trustScore: 83, accountType: 'Explorer' },
  { id: 'u18', fullName: 'Marta Nowak', username: 'marta.routes', avatar: 'https://picsum.photos/seed/gh-marta/200/200', coverImage: 'https://picsum.photos/seed/gh-marta-cover/1200/500', bio: 'Backpacker mixing buses, hostels, trails, and cheap food maps.', city: 'Kutaisi', explorerLevel: 'Silver Explorer', xp: 4870, rank: 55, badges: ['Budget Traveler', 'Traveler'], interests: ['hostels', 'routes', 'cheap eats'], followers: 1190, following: 380, postsCount: 135, visitedPlaces: 102, trustScore: 87, accountType: 'Explorer' },
  { id: 'u19', fullName: 'Tea Gvasalia', username: 'tea.clean.city', avatar: 'https://picsum.photos/seed/gh-tea/200/200', coverImage: 'https://picsum.photos/seed/gh-tea-cover/1200/500', bio: 'Patriot tasks, before-after cleanups, and neighborhood care.', city: 'Batumi', explorerLevel: 'Gold Explorer', xp: 5900, rank: 43, badges: ['Patriot', 'Community Helper'], interests: ['cleanup', 'parks', 'community'], followers: 860, following: 210, postsCount: 104, visitedPlaces: 73, trustScore: 98, accountType: 'Patriot' },
  { id: 'u20', fullName: 'Oto Kapanadze', username: 'oto.hosts', avatar: 'https://picsum.photos/seed/gh-oto/200/200', coverImage: 'https://picsum.photos/seed/gh-oto-cover/1200/500', bio: 'Guesthouse owner tracking loyal visitors and local hiking groups.', city: 'Mestia', explorerLevel: 'Bronze Explorer', xp: 1540, rank: 219, badges: ['Business Starter'], interests: ['guesthouses', 'hiking', 'business'], followers: 520, following: 145, postsCount: 35, visitedPlaces: 22, trustScore: 86, accountType: 'Business Owner' },
  { id: 'u21', fullName: 'Maka Robakidze', username: 'maka.events', avatar: 'https://picsum.photos/seed/gh-maka/200/200', coverImage: 'https://picsum.photos/seed/gh-maka-cover/1200/500', bio: 'Event lover collecting workshops, markets, concerts, and meetups.', city: 'Tbilisi', explorerLevel: 'Silver Explorer', xp: 5240, rank: 50, badges: ['Event Addict', 'Social Connector'], interests: ['events', 'markets', 'meetups'], followers: 1320, following: 470, postsCount: 167, visitedPlaces: 91, trustScore: 88, accountType: 'Explorer' },
  { id: 'u22', fullName: 'Andria Megrelishvili', username: 'andria.new', avatar: 'https://picsum.photos/seed/gh-andria/200/200', coverImage: 'https://picsum.photos/seed/gh-andria-cover/1200/500', bio: 'New here. Building my first map.', city: 'Tbilisi', explorerLevel: 'Bronze Explorer', xp: 80, rank: 980, badges: [], interests: ['cafes', 'events'], followers: 12, following: 31, postsCount: 2, visitedPlaces: 3, trustScore: 62, accountType: 'New User' },
  { id: 'u23', fullName: 'Natia Meskhi', username: 'natia.foodnotes', avatar: 'https://picsum.photos/seed/gh-natia/200/200', coverImage: 'https://picsum.photos/seed/gh-natia-cover/1200/500', bio: 'Detailed food notes, menu photos, and no-drama recommendations.', city: 'Kutaisi', explorerLevel: 'Silver Explorer', xp: 4430, rank: 64, badges: ['Top Reviewer', 'Food Scout'], interests: ['restaurants', 'reviews', 'desserts'], followers: 910, following: 260, postsCount: 130, visitedPlaces: 88, trustScore: 95, accountType: 'Explorer' },
  { id: 'u24', fullName: 'Alex Johnson', username: 'alex.weekends', avatar: 'https://picsum.photos/seed/gh-alex/200/200', coverImage: 'https://picsum.photos/seed/gh-alex-cover/1200/500', bio: 'Weekend traveler based in Tbilisi. I say yes to group plans too fast.', city: 'Tbilisi', explorerLevel: 'Bronze Explorer', xp: 2680, rank: 146, badges: ['Weekend Explorer'], interests: ['weekend trips', 'groups', 'wine'], followers: 560, following: 420, postsCount: 66, visitedPlaces: 51, trustScore: 82, accountType: 'Explorer' },
  { id: 'u25', fullName: 'Lizi Chanturia', username: 'lizi.beautyspots', avatar: 'https://picsum.photos/seed/gh-lizi/200/200', coverImage: 'https://picsum.photos/seed/gh-lizi-cover/1200/500', bio: 'Beauty salons, self-care days, brunch, and reward hunting.', city: 'Batumi', explorerLevel: 'Bronze Explorer', xp: 2300, rank: 157, badges: ['Reward Hunter'], interests: ['beauty', 'brunch', 'rewards'], followers: 740, following: 510, postsCount: 70, visitedPlaces: 44, trustScore: 79, accountType: 'Explorer' },
  { id: 'u26', fullName: 'Gvantsa Khvedelidze', username: 'gvantsa.study', avatar: 'https://picsum.photos/seed/gh-gvantsa/200/200', coverImage: 'https://picsum.photos/seed/gh-gvantsa-cover/1200/500', bio: 'Student organizer sharing public lectures and calm reading rooms.', city: 'Tbilisi', explorerLevel: 'Bronze Explorer', xp: 1190, rank: 251, badges: ['Student Scout'], interests: ['lectures', 'libraries', 'free events'], followers: 285, following: 204, postsCount: 28, visitedPlaces: 25, trustScore: 77, accountType: 'Student' },
  { id: 'u27', fullName: 'Rati Skhirtladze', username: 'rati.trails', avatar: 'https://picsum.photos/seed/gh-rati/200/200', coverImage: 'https://picsum.photos/seed/gh-rati-cover/1200/500', bio: 'Trail runner posting maps, elevation notes, and weather reality checks.', city: 'Borjomi', explorerLevel: 'Gold Explorer', xp: 9300, rank: 12, badges: ['Mountain Lover', 'Fitness Streak'], interests: ['trail running', 'hiking', 'parks'], followers: 1545, following: 278, postsCount: 198, visitedPlaces: 145, trustScore: 96, accountType: 'Creator' },
  { id: 'u28', fullName: 'Rusudan Eristavi', username: 'ruso.courses', avatar: 'https://picsum.photos/seed/gh-ruso/200/200', coverImage: 'https://picsum.photos/seed/gh-ruso-cover/1200/500', bio: 'Language teacher hosting small courses in cozy city spaces.', city: 'Tbilisi', explorerLevel: 'Bronze Explorer', xp: 1680, rank: 206, badges: ['Teacher'], interests: ['courses', 'language', 'cafes'], followers: 605, following: 172, postsCount: 44, visitedPlaces: 33, trustScore: 91, accountType: 'Teacher' },
  { id: 'u29', fullName: 'Vato Kldiashvili', username: 'vato.roasters', avatar: 'https://picsum.photos/seed/gh-vato/200/200', coverImage: 'https://picsum.photos/seed/gh-vato-cover/1200/500', bio: 'Coffee shop owner testing QR rewards and recurring guest campaigns.', city: 'Tbilisi', explorerLevel: 'Bronze Explorer', xp: 980, rank: 332, badges: ['Business Starter'], interests: ['coffee', 'loyalty', 'business'], followers: 890, following: 118, postsCount: 27, visitedPlaces: 18, trustScore: 89, accountType: 'Business Owner' },
  { id: 'u30', fullName: 'Christine Meyer', username: 'christine.photos', avatar: 'https://picsum.photos/seed/gh-christine/200/200', coverImage: 'https://picsum.photos/seed/gh-christine-cover/1200/500', bio: 'Architecture, balconies, galleries, and slow city walks.', city: 'Tbilisi', explorerLevel: 'Silver Explorer', xp: 4760, rank: 57, badges: ['Hidden Spot Finder', 'Photographer'], interests: ['photography', 'galleries', 'architecture'], followers: 1740, following: 330, postsCount: 141, visitedPlaces: 96, trustScore: 90, accountType: 'Creator' }
];

const MOCK_STORIES = [
  { userId: 'u01', ring: 'live', label: 'LIVE' },
  { userId: 'u06', ring: 'event', label: '' },
  { userId: 'u07', ring: '', label: '' },
  { userId: 'u12', ring: '', label: '' },
  { userId: 'u08', ring: 'seen', label: '' },
  { userId: 'u02', ring: 'live', label: 'LIVE' },
  { userId: 'u19', ring: 'place', label: '' },
  { userId: 'u29', ring: 'event', label: '' },
  { userId: 'u30', ring: '', label: '' },
  { userId: 'u22', ring: 'seen', label: '' }
];

const MOCK_FEED_POSTS = [
  { id: 'p01', type: 'checkin', userId: 'u01', time: '18 min ago', place: 'Fabrika Tbilisi', category: 'Cafe', image: 'https://picsum.photos/seed/feed-fabrika-real/900/650', caption: 'Morning coffee turned into a 2-hour coworking session. Good noise, good people, and a perfect first check-in for today.', mood: 'Focused', withUsers: ['u03', 'u08'], xp: 35, likes: 128, comments: [{ userId: 'u03', text: 'This table near the window is my favorite.' }, { userId: 'u08', text: 'Was the Wi-Fi stable today?' }] },
  { id: 'p02', type: 'hiking', userId: 'u02', time: '1h ago', place: 'Juta Valley Trail', category: 'Hiking', image: 'https://picsum.photos/seed/feed-juta-trail/900/650', caption: 'Trail is dry until the last section. Bring layers. The view after the ridge is unreal today.', mood: 'Mountain mode', withUsers: ['u27', 'u24'], xp: 90, likes: 284, comments: [{ userId: 'u27', text: 'Confirming the wind after 2pm is serious.' }, { userId: 'u18', text: 'Saving this for next weekend.' }] },
  { id: 'p03', type: 'event', userId: 'u06', time: '2h ago', title: 'Fabrika Night Market', place: 'Fabrika Courtyard', image: 'https://picsum.photos/seed/feed-night-market/900/650', caption: 'Group plan is open for tonight. Food trucks, vintage sellers, and a small DJ set after 21:00.', going: ['u13', 'u21', 'u26'], xp: 45, likes: 201, comments: [{ userId: 'u21', text: 'I am bringing two friends.' }] },
  { id: 'p04', type: 'deal', userId: 'u29', time: '3h ago', place: 'Roasters Lab', category: 'Partner Cafe', image: 'https://picsum.photos/seed/feed-roasters-lab/900/650', caption: 'QR reward live today: scan your receipt and get +30 points plus every fifth espresso free.', mood: 'Reward claimed', xp: 30, likes: 96, comments: [{ userId: 'u25', text: 'Claimed mine this morning.' }, { userId: 'u11', text: 'Budget-friendly coffee run approved.' }] },
  { id: 'p05', type: 'review', userId: 'u04', time: '4h ago', place: 'Shavi Lomi', category: 'Restaurant', image: 'https://picsum.photos/seed/feed-shavi-review/900/650', caption: 'Review: seasonal menu is stronger than last month. Try the mushroom khinkali and ask for amber wine pairing.', mood: 'Top review', xp: 55, likes: 176, comments: [{ userId: 'u23', text: 'The mushroom khinkali note is accurate.' }, { userId: 'u10', text: 'Adding this to Friday dinner.' }] },
  { id: 'p06', type: 'challenge', userId: 'u08', time: '5h ago', title: 'Free Events Hunter', place: 'Tbilisi State University', image: 'https://picsum.photos/seed/feed-student-event/900/650', caption: 'Challenge completed: attended 3 free public lectures this week. Zero GEL, +120 XP, and one new study group.', mood: 'Challenge complete', xp: 120, likes: 77, comments: [{ userId: 'u26', text: 'This is exactly my kind of week.' }] },
  { id: 'p07', type: 'patriot', userId: 'u19', time: '6h ago', place: 'Batumi Boulevard', category: 'Patriot Task', image: 'https://picsum.photos/seed/feed-cleanup/900/650', caption: 'Before-after cleanup verified. 14 people joined, 9 bags collected, and the park path is usable again.', mood: 'Verified task', withUsers: ['u05', 'u21'], xp: 180, likes: 312, comments: [{ userId: 'u05', text: 'Huge respect. This should be a weekly mission.' }, { userId: 'u09', text: 'I can join the next Batumi task.' }] },
  { id: 'p08', type: 'photo', userId: 'u07', time: '8h ago', place: 'Sololaki Courtyard', category: 'Hidden Spot', image: 'https://picsum.photos/seed/feed-sololaki-yard/900/650', caption: 'Tiny courtyard, blue stairs, warm light. Please keep it respectful if you visit.', mood: 'Aesthetic spot', xp: 60, likes: 421, comments: [{ userId: 'u30', text: 'The composition is beautiful.' }, { userId: 'u12', text: 'Old Sololaki still has magic.' }] },
  { id: 'p09', type: 'group', userId: 'u24', time: '10h ago', title: 'Weekend Kakheti Route', place: 'Sighnaghi', image: 'https://picsum.photos/seed/feed-kakheti-group/900/650', caption: 'Open group plan: leave Saturday 09:00, Sighnaghi walk, winery lunch, sunset viewpoint. Budget version available.', going: ['u11', 'u14', 'u18'], xp: 40, likes: 133, comments: [{ userId: 'u11', text: 'I am in if we keep transport cheap.' }] },
  { id: 'p10', type: 'business', userId: 'u20', time: '12h ago', place: 'Mestia Svan Guesthouse', category: 'Guesthouse', image: 'https://picsum.photos/seed/feed-mestia-house/900/650', caption: 'New guesthouse reward: hikers who complete Chalaadi trail get free tea and +25 GeoHub points at check-in.', mood: 'Business offer', xp: 25, likes: 89, comments: [{ userId: 'u02', text: 'Good route incentive.' }, { userId: 'u18', text: 'Saved for my Mestia week.' }] },
  { id: 'p11', type: 'course', userId: 'u16', time: '14h ago', title: 'Saturday Photography Workshop', place: 'Dedaena Park', image: 'https://picsum.photos/seed/feed-course-photo/900/650', caption: 'Small workshop for beginners: phone photography, framing, and editing. Students get free spots through GeoHub.', going: ['u26', 'u30', 'u08'], xp: 35, likes: 101, comments: [{ userId: 'u30', text: 'Happy to help with the architecture section.' }] },
  { id: 'p12', type: 'new_user', userId: 'u22', time: '1d ago', place: 'Vake Park', category: 'First Check-in', image: 'https://picsum.photos/seed/feed-vake-first/900/650', caption: 'First check-in. Still figuring this out, but I like seeing the XP move.', mood: 'New explorer', xp: 15, likes: 22, comments: [{ userId: 'u01', text: 'Welcome! Start with nearby cafes and one easy challenge.' }] }
];

const MOCK_CHALLENGES = [
  { id: 'c01', icon: '☕', name: 'Cafe Weekend Warrior', xp: 150, progress: 66, participants: ['u01', 'u03', 'u08', 'u17', 'u29'] },
  { id: 'c02', icon: '🏔️', name: 'Mountain Conqueror', xp: 300, progress: 80, participants: ['u02', 'u27', 'u18', 'u24'] },
  { id: 'c03', icon: '🎟️', name: 'Free Events Hunter', xp: 120, progress: 100, participants: ['u08', 'u21', 'u26', 'u16'] },
  { id: 'c04', icon: '🧹', name: 'Patriot Cleanup', xp: 220, progress: 45, participants: ['u05', 'u19', 'u09', 'u21'] }
];

const MOCK_GROUP_ACTIVITIES = [
  { title: 'Mestia trail crew', participants: ['u02', 'u18', 'u20', 'u27'], plan: 'Chalaadi Glacier morning route' },
  { title: 'Study cafe circle', participants: ['u03', 'u08', 'u16', 'u26'], plan: 'Quiet cafe crawl for finals week' },
  { title: 'Night market people', participants: ['u06', 'u13', 'u21', 'u25'], plan: 'Fabrika Night Market at 20:30' }
];

window.MOCK_USERS = MOCK_USERS;
window.MOCK_STORIES = MOCK_STORIES;
window.MOCK_FEED_POSTS = MOCK_FEED_POSTS;
window.MOCK_CHALLENGES = MOCK_CHALLENGES;
window.MOCK_GROUP_ACTIVITIES = MOCK_GROUP_ACTIVITIES;
