// Generates web/src/ui/icons.js from @phosphor-icons/core.
// Only the icons listed here are bundled. Add a name, then run:
//   node web/tools/build-icons.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const REGULAR = `
  house magnifying-glass bell chat-circle-dots chat-circle chat-teardrop-text plus plus-circle
  map-trifold map-pin map-pin-line list x x-circle check check-circle caret-left caret-right caret-down caret-up
  arrow-left arrow-right arrow-up-right arrow-square-out dots-three dots-three-vertical
  heart thumbs-up smiley share-fat share-network bookmark-simple paper-plane-right paper-plane-tilt
  image images video-camera film-strip play play-circle pause speaker-high speaker-slash
  user users users-three user-plus user-minus user-check user-circle user-gear identification-card
  storefront buildings briefcase calendar-blank calendar-check ticket tag shopping-bag house-line
  gift trophy medal star coins wallet crown sparkle lightning fire
  gear sign-out sign-in lock lock-open eye eye-slash shield-check shield-warning flag warning info question
  globe-hemisphere-east translate moon sun desktop device-mobile
  trash pencil-simple copy link camera microphone phone phone-disconnect video
  funnel sliders-horizontal sort-ascending compass navigation-arrow crosshair
  clock hourglass chart-bar chart-line-up envelope at hash
  smiley-sad smiley-wink hand-waving handshake
  prohibit speaker-none bell-slash archive push-pin push-pin-slash
  squares-four rows grid-four circles-four
  arrow-clockwise arrows-clockwise upload-simple download-simple
  youtube-logo google-logo facebook-logo instagram-logo tiktok-logo whatsapp-logo telegram-logo
  currency-circle-dollar receipt credit-card bank
  graduation-cap wrench car hamburger coffee wine mountains tree island barbell first-aid bed
  confetti music-notes microphone-stage paint-brush book-open palette
  qr-code scan seal-check check-square square circle radio-button
  text-aa smiley-meh megaphone rocket-launch target stack
  note-pencil newspaper broadcast television-simple monitor-play
  magic-wand arrow-bend-up-left arrow-u-up-left
`;
const FILLED = `
  house heart bookmark-simple bell chat-circle-dots play-circle star user-circle users-three
  map-trifold storefront film-strip compass gift thumbs-up seal-check crown lightning fire
  check-circle map-pin push-pin smiley calendar-blank shopping-bag trophy video-camera
  television-simple monitor-play squares-four
`;

const base = 'node_modules/@phosphor-icons/core/assets';
const out = {};
const missing = [];
function inner(file) {
  const svg = readFileSync(file, 'utf8');
  return svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
}
for (const n of REGULAR.split(/\s+/).filter(Boolean)) {
  const f = `${base}/regular/${n}.svg`;
  if (existsSync(f)) out[n] = inner(f); else missing.push(n);
}
for (const n of FILLED.split(/\s+/).filter(Boolean)) {
  const f = `${base}/fill/${n}-fill.svg`;
  if (existsSync(f)) out[`${n}-fill`] = inner(f); else missing.push(n + '-fill');
}
if (missing.length) { console.error('Missing icons:', missing.join(', ')); process.exit(1); }
const body = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');
writeFileSync('web/src/ui/icons.js',
  `// Generated by web/tools/build-icons.mjs from @phosphor-icons/core (MIT). Do not edit.\n` +
  `export const ICONS = {\n${body}\n};\n`);
console.log(`wrote ${Object.keys(out).length} icons`);
